name: nightly.link

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove README file
        run: rm README.md

        
      - name: Remove .git dir
        run: rm -r .git
        
        
      - name: Remove .github dir
        run: rm -r .github
        
      - name: Remove .whitesource
        run: rm .whitesource
        
      - uses: actions/upload-artifact@v2
        with:
          name: BoxelRebound
          path: ./hack
